haystack:
  graphite:
     prefix: "haystack"
     address: "haystack.local" # set in /etc/hosts per instructions in haystack/deployment module
     port: 2003 # default Graphite port, rarely overridden, but can be overridden by env variable
     pollIntervalSeconds: 60
     queueSize: 10
